{{- if eq .Values.deploymentType "deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "syftbox-server.fullname" . }}
  labels:
    {{- include "syftbox-server.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "syftbox-server.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate  # Ensure no multiple pods attempting to use the same PV
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "syftbox-server.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "syftbox-server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        # For server, we don't specify a command to use the default
        ports:
        - name: http
          containerPort: {{ .Values.server.port }}
          protocol: TCP
        env:
        - name: SYFTBOX_SERVER_CONFIG_PATH
          value: {{ .Values.server.configPath | quote }}
        {{- if .Values.server.extraEnv }}
        {{- toYaml .Values.server.extraEnv | nindent 8 }}
        {{- end }}
        volumeMounts:
        - name: syftbox-data
          mountPath: /data
        - name: syftbox-data
          mountPath: /config/syftbox
          subPath: config
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      volumes:
      - name: syftbox-data
        persistentVolumeClaim:
        {{- if .Values.persistence.existingClaim }}
          claimName: {{ .Values.persistence.existingClaim }}
        {{- else }}
          claimName: {{ include "syftbox-server.fullname" . }}-pvc
        {{- end }}
      - name: syftbox-config
        configMap:
          name: {{ include "syftbox-server.fullname" . }}-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}